export const MULTIPLAYER = {
  MATCH_WAVES: 5,
  PVP_JOUST_POINTS: 1000,
  PVP_RESPAWN_TIME: 2000,
  PVP_TIE_ZONE: 5,
  PVP_BOUNCE_FORCE: 150,
  COUNTDOWN_SECONDS: 3,
  SERVER_TICK_RATE: 60,
  BROADCAST_RATE: 20,
  INTERP_DURATION: 50,
};
